<?php 
use \Bonz\CMS\Files;

$tmpUser = clone $view->author;
$article_category = $view->getMetaView()->article_category;
$article = $view->getMetaView()->getArticle();
$inCreation = empty($article_category->catid);?>
<div class="form-content">
	<table>
		<?php if (!$inCreation && $view->userIsAdmin()){?>
		<tr>
			<td><label><?php echo _('Category ID')?></label></td>
			<td><?php echo $article_category->catid?></td>
			<td>
				<table class="description">
					<?php $tmpUser->load('uid='.$article_category->cre_uid);?>
					<tr>
						<td><?php echo _('Created on')?></td>
						<td><label><?php echo date('d/m/Y H:i', strtotime($article_category->cre_date));?></label></td>
						<td><?php echo _('By')?></td>
						<td><label><?php echo $tmpUser->login;?></label></td>
					</tr>
					<?php $tmpUser->load('uid='.$article_category->upd_uid);?>
					<tr>
						<td><?php echo _('Last edited on')?></td>
						<td><label><?php echo date('d/m/Y H:i', strtotime($article_category->upd_date));?></label></td>
						<td><?php echo _('By')?></td>
						<td><label><?php echo $tmpUser->login;?></label></td>
					</tr>
				</table>
			</td>
		</tr>
		<?php }?>
		<tr>
			<td><label for="category_name"><?php echo _('Category name')?></label></td>
			<td colspan=4>
				<input type="text" class="text mandatory" id="category_name" name="category[name]" value="<?php if (!empty($article_category->name)) echo $article_category->name;?>" />
				<div class="description">
					128 <?php echo _('characters max.')?>
					<?php echo _('No HTML tags.')?>
				</div>
			</td>
		</tr>
		<tr>
			<td><label for="category_label"><?php echo _('Category label')?></label></td>
			<td colspan="2">
				<input type="text" class="text mandatory" id="category_label" name="category[label]" value="<?php if (!empty($article_category->label)) echo $article_category->label;?>" />
				<div class="description">
					128 <?php echo _('characters max.')?>
					<?php echo _('No HTML tags.')?><br />
					<?php echo _('A very short description.')?>
				</div>
			</td>
		</tr>
		<tr>
			<td><label for="category_fid"><?php echo _('Vignette')?></label></td>
			<td colspan="2">
				<!-- Block include for file upload -->
				<?php $view->file_upload = array('fid'=>$article_category->fid, 'object_name'=>'category');?>
				<?php echo $view->getBlock('admin/elements/file_upload')?>
			</td>
		</tr>
		<tr>
			<td><label for="parent_catid"><?php echo _('Parent category')?></label></td>
			<td>
				<select id="parent_catid" name="category[parent_catid]">
					<option value="0"><?php echo _('None')?></option>
					<?php echo $view->htmlOptGroupCategories?>
				</select>
				<div class="description"><?php echo _('Leave empty to define it as a super category.');?></div>
			</td>
		</tr>
	</table>
	<?php if (!$inCreation){?>
	<button type="submit" name="submit_category" class="validate"><?php echo _('Update only category informations')?></button>
	<br /><br />
	<?php }?>
	<h1><?php echo _('Article informations')?></h1>
	<table>
		<?php if (!$inCreation){?>
		<tr>
			<?php if ($view->userIsAdmin()){?>
			<td colspan="2">
				<label><?php echo _('Article ID')?></label>
				<?php echo $article->aid?>&nbsp;&nbsp;&nbsp;<a class="description" href="<?php echo WEB_ROOT.'/'.$article->request_uri;?>">(<span class="underline"><?php echo _('go to front page')?></span>)</a>
			</td>
			<?php }?>
			<td class="description">
				<table>
					<tr>
						<td><?php echo _('Edited on')?></td>
						<td><label><?php echo date('d/m/Y H:i', strtotime($article->edit_date));?></label></td>
						<td><?php echo _('By')?></td>
						<td><label><?php echo $view->author->login;?></label></td>
					</tr>
				</table>
			</td>
		</tr>
		<?php }?>
		<tr>
			<td><label for="article_title"><?php echo _('Title')?>*</label></td>
			<td>
				<input type="text" id="article_title" name="article[title]" class="text long mandatory" maxlength="128" value="<?php if (!empty($article->title)) echo $article->title;?>" />
				<div class="description">
					128 <?php echo _('characters max.')?>
					<?php echo _('No HTML tags.')?>
				</div>
			</td>
		</tr>
		<tr>
			<td class="aligntop"><label for="article_summary"><?php echo _('Summary')?>*</label></td>
			<td><textarea id="article_summary" name="article[summary]" class="short mandatory" maxlength="255"><?php if (!empty($article->summary)) echo $article->summary;?></textarea></td>
			<td class="aligntop description" colspan="2">
				255 <?php echo _('characters max.')?>
				<br /><br />
				<?php echo _('Must contain a little summary that will be displayed into the "latest news" box.')?>
			</td>
		</tr>
		
		<?php if ($view->userIsAdmin()){?>
		<tr>
			<td><label for="article_access"><?php echo _('Access level')?></label></td>
			<td>
				<input type="number" id="article_access" name="article[access]" class="text number short" min="0" max="4" value="<?php if (!empty($article->access)) echo $article->access;?>" />
				<div class="description">
					<?php echo _('Degree of accessibility: 1=Only for super-admin, 2=For administrators, empty=access for all')?>
				</div>
			</td>
		</tr>
		<?php }?>
		<tr>
			<td><label for="article_request_uri"><?php echo _('Url alias')?>*</label></td>
			<td>
				<input type="text" id="article_request_uri" name="article[request_uri]" class="text medium mandatory" maxlength="255" value="<?php if (!empty($article->request_uri)) echo $article->request_uri;?>" />
				<div class="description">
					255 <?php echo _('characters max.')?>
					<br />
					<span class="user_end_warning"><?php echo _('Url alias must be unique for each article.')?></span>
				</div>
			</td>
		</tr>
		<tr>
			<td><label for="article_view"><?php echo _('View template')?>*</label></td>
			<td>
				<select id="article_view" name="article[view]" class="mandatory">
					<option></option>
					<?php foreach ($view->cms_views as $tplView){?>
					<option value="<?php echo $tplView?>" <?php if (!empty($article->view) && $tplView==$article->view) echo 'selected';?>><?php echo $tplView?></option>
					<?php }?>
				</select>
				<div class="description">
					<?php echo _('These layouts are stored in "apps/templates/views/cms".')?>
				</div>
			</td>
		</tr>
		<tr>
			<td class="aligntop"><label for="article_body"><?php echo _('Body')?></label></td>
			<td><textarea id="article_body" name="article[body]" class="long"><?php if (!empty($article->body)) echo $article->body;?></textarea></td>
		</tr>
		<tr>
			<td class="aligntop"><label for="article_greeting_text"><?php echo _('Greeting text')?></label></td>
			<td><textarea id="article_greeting_text" name="article[greeting_text]" class="short"><?php if (!empty($article->greeting_text)) echo $article->greeting_text;?></textarea></td>
			<td class="aligntop description" colspan="2">
				200 <?php echo _('characters max.')?>
				<br /><br />
				<?php echo _('A litle ending message such as "Cheers!".')?>
			</td>
		</tr>
		<tr>
			<td class="aligntop"><label for="article_signature"><?php echo _('Signature')?></label></td>
			<td><textarea id="article_signature" name="article[signature]" class="short madatory"><?php echo !empty($article->signature) ? $article->signature : ($inCreation ? $_SESSION['REG_USER']['login'] : '');?></textarea></td>
			<td class="aligntop description" colspan="2">
				100 <?php echo _('characters max.')?>
				<br /><br />
				<?php echo _('Author signature.')?>
			</td>
		</tr>
		<tr>
			<td><label for="article_publish"><?php echo _('Published')?></label></td>
			<td><input type="checkbox" id="article_publish" name="article[publish]" <?php if (!empty($article->publish)) echo 'checked="checked"';?> /></td>
		</tr>
	</table>
	<?php if (!$inCreation){?>
	<button type="submit" name="submit_article" class="validate"><?php echo _('Update only article informations')?></button>
	<br /><br />
	<?php }?>
</div>