<?php 
use \FragTale\CMS\Files;

$tmpUser = clone $view->author;
$article_category = $view->getMetaView()->article_category;
$article = $view->getMetaView()->getArticle();
$inCreation = empty($article_category->catid);?>
<div class="form-content">
	<?php if (!$inCreation && $view->userIsAdmin()){?>
	<div class="description alignright">
		<?php $tmpUser->load('uid='.$article_category->cre_uid);?>
		<div>
			<?php echo _('Created on')?>
			<label><?php echo date('d/m/Y H:i', strtotime($article_category->cre_date));?></label>
			<?php echo _('By')?>
			<label><?php echo $tmpUser->login;?></label>
		</div>
		<?php $tmpUser->load('uid='.$article_category->upd_uid);?>
		<div>
			<?php echo _('Last edited on')?>
			<label><?php echo date('d/m/Y H:i', strtotime($article_category->upd_date));?></label>
			<?php echo _('By')?>
			<label><?php echo $tmpUser->login;?></label>
		</div>
	</div>
	<div class="form-elt">
		<div class="form-label mobile-stayinline"><label><?php echo _('Category ID')?></label></div>
		<div class="form-input mobile-stayinline"><?php echo $article_category->catid?></div>
	</div>
	<?php }?>
	
	<div class="form-elt">
		<div class="form-label"><label for="category_name"><?php echo _('Category name')?></label></div>
		<div class="form-input">
			<input type="text" class="text medium mandatory" id="category_name" name="category[name]" value="<?php if (!empty($article_category->name)) echo $article_category->name;?>" />
			<div class="description">
				128 <?php echo _('characters max.')?>
				<?php echo _('No HTML tags.')?>
			</div>
		</div>
	</div>
	
	<div class="form-elt">
		<div class="form-label"><label for="category_label"><?php echo _('Category label')?></label></div>
		<div class="form-input">
			<input type="text" class="text medium mandatory" id="category_label" name="category[label]" value="<?php if (!empty($article_category->label)) echo $article_category->label;?>" />
			<div class="description">
				128 <?php echo _('characters max.')?>
				<?php echo _('No HTML tags.')?><br />
				<?php echo _('A very short description.')?>
			</div>
		</div>
	</div>
	
	<div class="form-elt">
		<div class="form-label"><label for="category_fid"><?php echo _('Vignette')?></label></div>
		<div class="form-input">
			<!-- Block include for file upload -->
			<?php $view->file_upload = array('fid'=>$article_category->fid, 'object_name'=>'category');?>
			<?php echo $view->getBlock('admin/elements/file_upload')?>
		</div>
	</div>
	
	<div class="form-elt">
		<div class="form-label"><label for="parent_catid"><?php echo _('Parent category')?></label></div>
		<div class="form-input">
			<select id="parent_catid" name="category[parent_catid]">
				<option value="0"><?php echo _('None')?></option>
				<?php echo $view->htmlOptGroupCategories?>
			</select>
			<div class="description"><?php echo _('Leave empty to define it as a super category.');?></div>
		</div>
	</div>
	
	<?php if (!$inCreation){?>
	<div class="form-elt">
		<button type="submit" name="submit_category" class="validate"><?php echo _('Update only category informations')?></button>
	</div>
	<br /><br />
	<?php }?>
	
	
	<h1><?php echo _('Article informations')?></h1>
	
	<?php if (!$inCreation){?>
	<div class="description alignright">
		<?php echo _('Edited on')?> <label><?php echo date('d/m/Y H:i', strtotime($article->edit_date));?></label>
		<?php echo _('By')?> <label><?php echo $view->author->login;?></label>
	</div>
	
	<div class="form-elt">
		<?php if ($view->userIsAdmin()){?>
		<div class="form-label mobile-stayinline">
			<label><?php echo _('Article ID')?></label>
		</div>
		<?php }?>
		<div class="form-input mobile-stayinline">
			<?php echo $article->aid?>&nbsp;&nbsp;&nbsp;<a class="description add_new" href="<?php echo WEB_ROOT.'/'.$article->request_uri;?>"><?php echo _('go to front page')?></a>
		</div>
	</div>
	<?php }?>
	
	<div class="form-elt">
		<div class="form-label"><label for="article_title"><?php echo _('Title')?>*</label></div>
		<div class="form-input">
			<input type="text" id="article_title" name="article[title]" class="text long mandatory" maxlength="128" value="<?php if (!empty($article->title)) echo $article->title;?>" />
			<div class="description">
				128 <?php echo _('characters max.')?>
				<?php echo _('No HTML tags.')?>
			</div>
		</div>
	</div>
	
	<div class="form-elt">
		<div class="form-label"><label for="article_summary"><?php echo _('Summary')?>*</label></div>
		<div class="form-input">
			<textarea id="article_summary" name="article[summary]" class="short mandatory" maxlength="255"><?php
				if (!empty($article->summary)) echo $article->summary;?></textarea>
			<div class="description">
				255 <?php echo _('characters max.')?>
				<br />
				<?php echo _('Must contain a little summary that will be displayed into the "latest news" box.')?>
			</div>
		</div>
	</div>
	
	<?php if ($view->userIsAdmin()){?>
	<div class="form-elt">
		<div class="form-label"><label for="article_access"><?php echo _('Access level')?></label></div>
		<div class="form-input">
			<input type="number" id="article_access" name="article[access]" class="text number short" min="0" max="4" value="<?php if (!empty($article->access)) echo $article->access;?>" />
			<div class="description">
				<?php echo _('Degree of accessibility: 1=Only for super-admin, 2=For administrators, empty=access for all')?>
			</div>
		</div>
	</div>
	<?php }?>
	
	<div class="form-elt">
		<div class="form-label"><label for="article_request_uri"><?php echo _('Url alias')?>*</label></div>
		<div class="form-input">
			<input type="text" id="article_request_uri" name="article[request_uri]" class="text medium mandatory" maxlength="255" value="<?php if (!empty($article->request_uri)) echo $article->request_uri;?>" />
			<div class="description">
				255 <?php echo _('characters max.')?>
				<br />
				<span class="user_end_warning"><?php echo _('Url alias must be unique for each article.')?></span>
			</div>
		</div>
	</div>
	
	<div class="form-elt">
		<div class="form-label"><label for="article_view"><?php echo _('View template')?>*</label></div>
		<div class="form-input">
			<select id="article_view" name="article[view]" class="mandatory">
				<option></option>
				<?php foreach ($view->cms_views as $tplView){?>
				<option value="<?php echo $tplView?>" <?php if (!empty($article->view) && $tplView==$article->view) echo 'selected';?>><?php echo $tplView?></option>
				<?php }?>
			</select>
			<div class="description">
				<?php echo _('These layouts are stored in "apps/templates/views/cms".')?>
			</div>
		</div>
	</div>
	
	<div class="form-elt">
		<div><label for="body"><?php echo _('Body')?></label></div>
		<div><textarea id="body" name="article[body]" class="long ckeditor"><?php if (!empty($article->body)) echo $article->body;?></textarea></div>
	</div>
	
	<div class="form-elt">
		<div class="form-label mobile-stayinline"><label for="article_publish"><?php echo _('Published')?></label></div>
		<div class="form-input mobile-stayinline"><input type="checkbox" id="article_publish" name="article[publish]" <?php if (!empty($article->publish)) echo 'checked="checked"';?> /></div>
	</div>
	<?php if (!$inCreation){?>
	<div class="form-elt">
		<button type="submit" name="submit_article" class="validate"><?php echo _('Update only article informations')?></button>
	</div>
	<?php }?>
</div>