<?php
use \FragTale\CMS\Files;
$objectName = !empty($view->getParentView()->file_upload['object_name']) ? $view->getParentView()->file_upload['object_name'] : 'item';
$input_id	= 'file_'.rand(0, 1000000);
$fid		= !empty($view->getParentView()->file_upload['fid']) ? $view->getParentView()->file_upload['fid'] : null;
$file = new Files();
if ($fid){
	$file->load("fid='$fid'");
}?>
<div class="file_item">
	<div class="inline">
		<div class="description"><?php echo _('Upload a file')?></div>
		<input type="file" class="file" id="<?php echo $objectName?>_fid" name="<?php echo $objectName?>[fid]" value="" />
		<div class="description"><?php echo _('Or choose an existing one (auto-completion)')?></div>
		<input type="text" class="text autocomplete" id="<?php echo $input_id?>" value="<?php echo $file->filename?>" />
		<div class="autocompletebox <?php echo $input_id?>"></div>
		<input type="hidden" id="hidden_<?php echo $input_id?>" name="<?php echo $objectName?>[selected_fid]" />
	</div><?php
	
	if ($fid){?>
	<div class="inline aligntop pic_toggle description">
		<div class="bon_toggler inline" target="fid_<?php echo $file->fid?>"><?php echo _('Visualize')?></div>
		<div id="fid_<?php echo $file->fid?>" class="collapsed">
			<?php if (stripos($file->mime_type, 'image')===false){?>
			<object class="preview" type="<?php echo $file->mime_type?>" data="<?php echo WEB_ROOT.'/'.$file->path;?>"></object>
			<?php }else{?>
			<img class="preview" src="<?php echo WEB_ROOT.'/'.$file->path;?>" />
			<?php }?>
		</div>
	</div>
	<?php }?>
</div>