<div class="main_footer">
	<div class="footer_col separate">
		<p><?php echo _('Sitemap')?></p>
		<ul class="footer">
			<li>
				<a href="<?php echo WEB_ROOT;?>"><?php echo _('Home')?></a>
			</li>
			<?php if (!empty($view->getMetaView()->category_tree)) foreach ($view->getMetaView()->category_tree as $category){?>
			<li>
				<a href="<?php echo WEB_ROOT.'/'.$category['data']['request_uri']?>"><?php echo $category['data']['name']?></a>
				<?php if (!empty($category['children'])){?>
				<ul>
					<?php foreach ($category['children'] as $subCategory){?>
					<li><a href="<?php echo WEB_ROOT.'/'.$subCategory['data']['request_uri']?>"><?php echo $subCategory['data']['name']?></a>
					<?php }?>
				</ul>
				<?php }?>
			</li>
			<?php }?>
			<?php if (!empty($view->mainArticles)) foreach ($view->mainArticles as $article){?>
			<li>
				<a href="<?php echo WEB_ROOT.'/'.$article['request_uri'];?>"><?php echo $article['title']?></a>
			</li>
			<?php }?>
		</ul>
	</div>
	<div class="footer_col separate">
		<p><?php echo _('Recommended links')?></p>
		<ul class="footer">
			<li>
				<a href="http://alimentation.gouv.fr/manger-bio">Mangez bio</a>
			</li>
			<li>
				<a href="http://www.fatalspicards.com/">Les Fatals Picards</a>
			</li>
		</ul>
	</div>
	<div class="footer_col">
		<div class="footer_ending">
			This website is powered by the BoN Team founders, based on a home-made Open Source CMS. Ask for us.
			<br />
			Toulouse-Paris-Lyon, France.
		</div>
	</div>
</div>
