<?php $catTree = !empty($view->getMetaView()->category_tree) ? $view->getMetaView()->category_tree : array();?>
<div class="main_footer">
	<p><?php echo _('Sitemap')?></p>
	<div>
		<ul class="footer">
			<li>
				<a href="<?php echo WEB_ROOT;?>"><b><?php echo _('Home')?></b></a>
			</li>
			<?php if (!empty($view->mainArticles)) foreach ($view->mainArticles as $article){?>
			<li>
				<a href="<?php echo WEB_ROOT.'/'.$article['request_uri'];?>"><b><?php echo $article['title']?></b></a>
			</li>
			<?php }?>
		</ul>
		<?php foreach ($catTree as $category){?>
		<ul class="footer">
			<li>
				<a href="<?php echo WEB_ROOT.'/'.$category['data']['request_uri']?>"><b><?php echo $category['data']['name']?></b></a>
				<?php if (!empty($category['children'])){?>
				<ul>
					<?php foreach ($category['children'] as $subCategory){?>
					<li><a href="<?php echo WEB_ROOT.'/'.$subCategory['data']['request_uri']?>"><?php echo $subCategory['data']['name']?></a>
					<?php }?>
				</ul>
				<?php }?>
			</li>
		</ul>
		<?php }?>
	</div>
	<div class="footer_ending">
		<!-- This website is powered by the BoN Team founders, based on a home-made Open Source CMS. Ask for us.
		<br />
		Toulouse-Paris-Lyon, France. -->
	</div>
</div>
