<?php echo $view->getBlock('blocks/category_carousel')?>

<div class="banner">
	<a class="home-link" href="<?php echo WEB_ROOT?>">
		<h1>CMS</h1>
		<h2>FragTale</h2>
	</a>
	<?php if ($view->userIsLogged()){?>
	<div class="loggedin">
		<div class="inline alignmiddle user_login">
			<?php echo $view->getUser()->login.',';?>
			<?php if ($view->userIsAdmin()){?>
			<a href="<?php echo ADMIN_WEB_ROOT?>" target="_blank"><?php echo _('go to admin panel')?></a>
			<?php }elseif ($view->userIsLogged()){?>
			<a href="<?php echo ADMIN_WEB_ROOT?>/user/edit?uid=<?php echo $view->getUser()->uid?>" target="_blank"><?php echo _('your profile')?></a>
			<?php }?>
		</div>
	</div>
	<?php }?>
</div>

<nav>
	<ul class="left">
		<?php foreach ($view->menu as $page=>$title){?>
		<li class="mainmenu">
			<a href="<?php echo WEB_ROOT?>/<?php echo $page!='home'? $page : ''?>" class="mainmenu_link <?php
				echo $page==$view->current ? 'current' : '';?> <?php
				echo $page=='logout' ? 'logout' : ''?>">
				<?php echo $title?>
			</a>
		</li>
		<?php }?>
	</ul>
</nav>

<?php echo $view->getBlock('blocks/subcategory_carousel')?>