<?php if (!empty($view->files['whole_db_list'])){?>
<form method="post">
	<h1><?php echo _('Uploaded files stored into the database')?></h1>
	<?php echo $view->getBlock('admin/elements/datagrid_searches')?>
	<table class="datagrid">
		<thead>
			<tr>
				<?php foreach (array('fid'=>'ID', 'filename'=>_('Name'), 'mime_type'=>_('Mime type')) as $field=>$title){?>
				<th><a href="#" id="field_<?php echo $field?>" class="<?php if (!empty($_GET['order']) && $_GET['order']==$field) echo 'current';?>"><?php echo $title?></a></th>
				<?php }?>
				<th><?php echo _('Preview')?></th>
				<th><?php echo _('Delete')?></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($view->files['whole_db_list'] as $file){?>
			<tr class="<?php if (empty($trclass)) $trclass = 'iter'; else $trclass = ''; echo $trclass;?>">
				<td><?php echo $file['fid']?></td>
				<td><?php echo $file['filename']?></td>
				<td><?php echo $file['mime_type']?></td>
				<td>
					<?php if (stripos($file['mime_type'], 'image')!==false){?>
					<div class="pic_toggle">
						<div class="bon_toggler" target="fid_<?php echo $file['fid']?>"><?php echo _('Visualize')?></div>
						<div id="fid_<?php echo $file['fid']?>" class="collapsed">
							<div><em><?php echo $file['filename']?></em></div>
							<img class="preview" src="<?php echo WEB_ROOT.'/'.$file['path'];?>" />
						</div>
					</div><?php
					}
					else echo _('N/A');?>
				</td>
				<td class="center">
					<input type="checkbox" name="delete[<?php echo $file['fid']?>]" />
				</td>
			</tr>
			<?php }?>
		</tbody>
		<tr class="iter">
			<td colspan="4"></td>
			<td class="aligncenter">
				<button type="submit" class="validate delete" onclick="return confirm('<?php echo _('Confirm this action');?>');"><?php echo _('Del.')?></button>
			</td>
		</tr>
	</table>
</form>
<br><br>
<?php }?>

<!-- Upload de fichier -->
<form method="post" enctype="multipart/form-data" class="multiple_file_upload">
	<h1><?php echo _('Upload and list new files')?></h1>
	<div class="vignettes_container">
		<div class="vignette">
			<div class="pic_cont">
				<label>
					<?php echo _('Please click or drop your file here.');?>
				</label>
				<input type="file" name="file[]" class="file "/>
			</div>
		</div>
	</div>
	<button type="submit" class="add_new validate upd" name="upload"><?php echo _('Upload')?></button>
</form>

<?php if ($view->userIsSuperAdmin()){?>
<?php if (!empty($view->files['not_in_db'])){?>
<br><br>
<form method="post">
	<h1><?php echo _('Physical files that are not registered into the database')?></h1>
	<table class="datagrid">
		<thead>
			<tr>
				<th><?php echo _('File name')?></th>
				<th><?php echo _('Type|Path')?></th>
				<th><?php echo _('Preview')?></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($view->files['not_in_db'] as $path=>$filename){
				$exp	= explode(' ', $path);
				$type	= $exp['0'];
				$path	= $exp[1];
				$exp	= explode('/', $type);
				$isImg	= $exp[0]=='image';?>
			<tr>
				<td><?php echo $filename?></td>
				<td><?php echo $path?></td>
				<td>
					<div class="pic_toggle">
						<?php if ($isImg){?>
						<div class="bon_toggler" target="file_<?php echo $filename?>"><?php echo _('Visualize')?></div>
						<div id="file_<?php echo $filename?>" class="collapsed">
							<div><em><?php echo $filename?></em></div>
							<img class="preview" src="<?php echo WEB_ROOT.'/'.$path;?>" />
						</div>
						<?php }else echo _('N/A')?>
					</div>
				</td>
			</tr>
			<?php }?>
		</tbody>
		<tr class="iter">
			<td colspan="2"></td>
			<td class="aligncenter">
				<a class="add_new validate" href="<?php echo ADMIN_WEB_ROOT?>/file_manager/diffs"><?php echo _('Manage')?></a>
			</td>
		</tr>
	</table>
</form>
<?php }?>

<?php if (!empty($view->files['not_in_dir'])){?>
<br><br>
<form method="post">
	<h1><?php echo _('Files in database that are not physically presents')?></h1>
	<table class="datagrid">
		<thead>
			<tr>
				<th>ID</th>
				<th><?php echo _('File name')?></th>
				<th><?php echo _('Mime type')?></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($view->files['not_in_dir'] as $file){?>
			<tr>
				<td><?php echo $file['fid']?></td>
				<td><?php echo $file['filename']?></td>
				<td><?php echo $file['mime_type']?></td>
			</tr>
			<?php }?>
		</tbody>
		<tr class="iter">
			<td colspan="2"></td>
			<td class="aligncenter">
				<a class="add_new validate" href="<?php echo ADMIN_WEB_ROOT?>/file_manager/diffs"><?php echo _('Manage')?></a>
			</td>
		</tr>
	</table>
</form>
<?php }?>

<?php if (empty($view->files['not_in_dir']) && empty($view->files['not_in_db'])){?>
<div class="description" style="margin-top: 5em">
	<h1><?php echo _('Check for unregistered files')?></h1>
	<a class="add_new validate" href="<?php echo ADMIN_WEB_ROOT?>/file_manager/diffs">>>Go</a>
	<br /><br />
	<span class="user_end_warning"><?php echo _('Be aware that this process can take a while if your database is huge.')?></span>
</div>
<?php }?>

<?php }?>