<?php if (!empty($view->files['not_in_db'])){?>
<form method="post">
	<h1><?php echo _('Physical files that are not registered into the database')?></h1>
	<table class="datagrid">
		<thead>
			<tr>
				<th><?php echo _('File name')?></th>
				<th><?php echo _('Type|Path')?></th>
				<th><?php echo _('Preview')?></th>
				<th><?php echo _('Add')?></th>
				<th><?php echo _('Erase')?></th>
			</tr>
		</thead>
		<tbody>
			<?php $i=0;foreach ($view->files['not_in_db'] as $path=>$filename){
				$paths	= explode(' ', $path);
				$type	= reset($paths);
				$isImg	= stripos($type, 'image')!==false;?>
			<tr class="<?php echo $i%2 ? '' : 'iter'?>">
				<td><?php echo $filename?></td>
				<td><?php echo $path?></td>
				<td>
					<?php if ($isImg){?>
					<div class="pic_toggle">
						<div class="bon_toggler" target="file_<?php echo $i?>"><?php echo _('Visualize')?></div>
						<div id="file_<?php echo $i?>" class="collapsed">
							<div><em><?php echo $filename?></em></div>
							<img class="preview" src="<?php echo WEB_ROOT.'/uploads/'.$type.'/'.$filename;?>" />
						</div>
					</div><?php
					}
					else echo _('N/A');?>
				</td>
				<td class="center"><input type="checkbox" name="add[<?php echo $filename;?>]" /></td>
				<td class="center"><input type="checkbox" name="erase[<?php echo $filename;?>]" /></td>
			</tr>
			<?php $i++;}?>
		</tbody>
		<tr class="iter">
			<td colspan="3"></td>
			<td colspan="2" class="aligncenter">
				<button type="submit" class="validate upd" onclick="return confirm('<?php echo _('Confirm this action');?>');"><?php echo _('Submit')?></button>
			</td>
		</tr>
	</table>
</form>
<br><br>
<?php }?>

<?php if (!empty($view->files['not_in_dir'])){?>
<form method="post">
	<h1><?php echo _('Files in database that are not physically presents')?></h1>
	<table class="datagrid">
		<thead>
			<tr>
				<th>ID</th>
				<th><?php echo _('File name')?></th>
				<th><?php echo _('Mime type')?></th>
				<th style="width: 129px"><?php echo _('Remove from database')?></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($view->files['not_in_dir'] as $i=>$file){?>
			<tr class="<?php echo $i%2 ? '' : 'iter'?>">
				<td><?php echo $file['fid']?></td>
				<td><?php echo $file['filename']?></td>
				<td><?php echo $file['mime_type']?></td>
				<td class="aligncenter"><input type="checkbox" name="delete[<?php echo $file['fid'];?>]" /></td>
			</tr>
			<?php }?>
		</tbody>
		<tr class="iter">
			<td colspan="3"></td>
			<td class="aligncenter">
				<button type="submit" class="delete" onclick="return confirm('<?php echo _('Confirm this action');?>');"><?php echo _('Delete')?></button>
			</td>
		</tr>
	</table>
</form>
<?php }?>
<?php if (empty($view->files['not_in_dir']) && empty($view->files['not_in_db'])){?>
<h1><?php echo _('Status: OK')?></h1>
<?php }?>