<h1 class="article-title"><?php echo _('Define a new password')?></h1>
<article class="article-content">
	<form method="post">
		<div class="description"><?php echo _('Please, enter your new password. Then, validate.')?></div>
		<table>
			<tr>
				<td>
					<label for="password" class="italic"><?php echo _('New password')?></label>
				</td>
				<td>
					<input type="password" id="password" name="password" class="text medium mandatory" autofocus autocomplete="off" />
				</td>
			</tr>
			<tr>
				<td>
					<label for="chk_pwd" class="italic"><?php echo _('Retype')?></label>
				</td>
				<td>
					<input type="password" id="chk_pwd" class="text medium mandatory" />
				</td>
			</tr>
			<tr>
				<td></td>
				<td><button type="submit" class="validate"><?php echo _('Validate')?></button></td>
			</tr>
		</table>
	</form>
</article>
