<h1 class="article-title"><?php echo $view->getArticle()->title?>Bienvenue</h1>
<article class="article-content">
Site en construction<br>
	<!-- <?php /*echo $view->getArticle()->body?>
	<div class="greetings">
		<?php echo $view->getArticle()->greeting_text?><br />
		<b class="signature"><?php echo $view->getArticle()->signature*/?></b>
	</div>
	 -->
	 <img src="http://bandofnuts.fr//uploads/image/png/toto-2.png" style="width:100%"/>
</article>
