<h1 class="article-title"><?php echo _('I\'ve forgot my password')?></h1>
<article class="article-content">
	<form method="post">
		<div><?php echo _('Please, enter the email address with which you registered or enter your username in the textbox below. Then, validate.')?></div>
		<br>
		<div><?php echo _('An email will be sent to your mailbox intending to authentify your action. The mail might be placed in your spam box.')?></div>
		<br><br>
		<div>
			<label for="email" class="italic"><?php echo _('Email address')?></label>
			<input type="text" id="user" name="user" class="text third login mandatory" autofocus />&nbsp;&nbsp;
			<button type="submit" class="validate"><?php echo _('Validate')?></button>
		</div>
	</form>
</article>
