<h1><?php echo _('Edit article informations');?></h1>
<form class="edit-form" method="post" enctype="multipart/form-data">
	<?php echo $view->getBlock('admin/forms/article');?>
	<button type="submit" name="upd" class="validate upd" title="<?php echo _('Just save it')?>"><?php echo _('Update')?></button>
	<button type="submit" name="historicize" class="validate" title="<?php echo _('Store this article version')?>"><?php echo _('Historicize')?></button>
	<button type="submit" name="upd_historicize" class="validate" title="<?php echo _('Update and store this article version')?>"><?php echo _('Update and historicize')?></button>
</form>