<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title><?php echo $view->getTitle()?></title>
		<?php echo $view->getCssTags()?>
		<script type="text/javascript">
			var WEB_ROOT = '<?php echo WEB_ROOT?>';
			var ADMIN_WEB_ROOT = '<?php echo ADMIN_WEB_ROOT?>';
		</script>
	</head>
	
	<body class="admin <?php echo str_replace(array('/', ' '), '-', $view->getViewName());?>">
	<div class="admin-body">
		<div class="page">
		
			<?php if ($view->userIsLogged()) echo $view->getBlock('admin/header');?>
			
			<section class="content <?php if (!$view->userIsLogged()) echo 'centerblock';?>">
				<?php echo $view;?>
				<?php if ($msgs = $view->getUserEndMsgs()){?>
				<div id="user_end_msg_container">
					<span class="close" onclick="document.getElementById('user_end_msg_container').style.display='none';">&nbsp;</span>
					<?php echo $msgs;?>
				</div>
				<?php }?>
			</section>
			
			<section class="footer">
				<?php echo $view->getBlock('admin/footer')?>
			</section>
			
		</div>
	</div>
	<script type="text/javascript" src="<?php echo WEB_ROOT?>/js/jquery.min.js"></script>
	<!--[if lte IE 8]>
		<script type="text/javascript">
			alert('Cet espace n\'est pas compatible avec les versions Internet Explorer < 9');
			location = '<?php echo WEB_ROOT?>';
		</script>
	<![endif]-->
	<?php echo $view->getJsTags()?>
	</body>
</html>